version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile
    container_name: Docker
    image: docker:local
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./Dockerfiles/php.ini:/usr/local/etc/php/conf.d/dev.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"